version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
    working_directory: ~/sharebrain
    steps:
      - checkout:
          path: ~/sharebrain
      - ruby/install-deps
  test:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: share_brain_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/sharebrain
    steps:
      - checkout:
          path: ~/sharebrain
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test
  deploy:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  deploy:
    executor: heroku/default
    parameters:
      env:
        type: enum
        enum: [ "staging", "production" ]
      heroku_app_name:
        type: string
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
    environment:
      - RAILS_ENV: production
      - HEROKU_APP_NAME: sharebrain-rtr

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          name: deploy_staging
          env: staging
          heroku_app_name: sharebrain-rtr
          filters:
            branches:
              only: [dev, main]
