development:
  adapter: mysql2
  encoding: utf8
  database: share_brain_development
  pool: 5
  username: root
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: share_brain_test
  pool: 5
  username: root
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: share_brain_production
  pool: 5
  username: root
  password: password
  host: localhost
